//! The diesel schema. Normally generated by `diesel print-schema`.
//!
//! `diesel::table!` emits undocumented items, and this file is generated, so
//! `missing_docs` is switched off here rather than in every crate. Every
//! consumer needs the same line on its own schema module.
#![allow(missing_docs)]

diesel::table! {
    todos (id) {
        id -> Integer,
        title -> Text,
        done -> Bool,
        created_at -> Timestamp,
        updated_at -> Timestamp,
        deleted_at -> Nullable<Timestamp>,
        version -> Integer,
    }
}
